name: CI/CD doppler_secrets

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Doppler CLI
      run: |
        sudo curl -Ls https://cli.doppler.com/install.sh | sudo sh

    - name: Doppler Fetch secrets
      env:
        DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      run: |
        doppler secrets download --format env --no-file > doppler_secrets.env
        echo "Содержимое doppler_secrets.env:"
        cat doppler_secrets.env
        set -a
        source doppler_secrets.env
        set +a
        env | grep -E 'DATABASE_PASSWORD|API_KEY|ENCRYPTION_KEY|AUTH_TOKEN|SERVER_ENDPOINT'

    - name: Check and Use secrets securely
      run: |
        echo "Проверяем наличие секретов"
        if [ -z "$DATABASE_PASSWORD" ]; then echo "DATABASE_PASSWORD is not set"; exit 1; fi
        if [ -z "$API_KEY" ]; then echo "API_KEY is not set"; exit 1; fi
        if [ -z "$ENCRYPTION_KEY" ]; then echo "ENCRYPTION_KEY is not set"; exit 1; fi
        if [ -z "$AUTH_TOKEN" ]; then echo "AUTH_TOKEN is not set"; exit 1; fi
        if [ -z "$SERVER_ENDPOINT" ]; then echo "SERVER_ENDPOINT is not set"; exit 1; fi
        echo "Все секреты успешно загружены и установлены"
        # Пример использования секретов
        echo "Подключаемся к базе данных"
        echo "Секреты не отображаются в логах"
        # psql -h your_database_host -U your_database_user -d your_database_name -W $DATABASE_PASSWORD < your_sql_script.sql
        echo "Выполняем вызов API"
        # curl -H "Authorization: Bearer $API_KEY" $SERVER_ENDPOINT
