name: CI/CD doppler_secrets

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Doppler CLI
      run: |
        sudo curl -Ls https://cli.doppler.com/install.sh | sudo sh

    - name: Doppler Fetch and Export secrets
      env:
        DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      run: |
        eval $(doppler secrets download --no-log --format env)
        env | grep -E 'DATABASE_PASSWORD|API_KEY|ENCRYPTION_KEY|AUTH_TOKEN|SERVER_ENDPOINT'

    - name: Use secrets
      run: |
        echo "Show secrets in logs"
        echo "DATABASE_PASSWORD=$DATABASE_PASSWORD"
        echo "API_KEY=$API_KEY"
        echo "ENCRYPTION_KEY=$ENCRYPTION_KEY"
        echo "AUTH_TOKEN=$AUTH_TOKEN"
        echo "SERVER_ENDPOINT=$SERVER_ENDPOINT"
